// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/customer-login/BoldBlocks.tsx": () => import("../components/mockups/customer-login/BoldBlocks.tsx"),
  "./components/mockups/customer-login/CenteredStack.tsx": () => import("../components/mockups/customer-login/CenteredStack.tsx"),
  "./components/mockups/customer-login/Current.tsx": () => import("../components/mockups/customer-login/Current.tsx"),
  "./components/mockups/customer-login/SplitSpotlight.tsx": () => import("../components/mockups/customer-login/SplitSpotlight.tsx")
};
