// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/account-overview/BoldBlocks.tsx": () => import("../components/mockups/account-overview/BoldBlocks.tsx"),
  "./components/mockups/account-overview/CalmBrutalist.tsx": () => import("../components/mockups/account-overview/CalmBrutalist.tsx"),
  "./components/mockups/account-overview/Current.tsx": () => import("../components/mockups/account-overview/Current.tsx"),
  "./components/mockups/account-overview/PlayfulDash.tsx": () => import("../components/mockups/account-overview/PlayfulDash.tsx")
};
